// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYwhEMnsl5g7XBUl0eqSJWynmnM016QLw',
    appId: '1:782940469195:web:03759e2588c46e0c3a684e',
    messagingSenderId: '782940469195',
    projectId: 'mobiledoc-a1e97',
    authDomain: 'mobiledoc-a1e97.firebaseapp.com',
    storageBucket: 'mobiledoc-a1e97.firebasestorage.app',
    measurementId: 'G-XFK2BDV9SQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKWlexIJpuNfdjcEMY4IYilpeQxod2Zmg',
    appId: '1:782940469195:android:cd5a250e038c7ed33a684e',
    messagingSenderId: '782940469195',
    projectId: 'mobiledoc-a1e97',
    storageBucket: 'mobiledoc-a1e97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmuAz5g02A2vKneqfSR8jTGWA7tkUKYxc',
    appId: '1:782940469195:ios:775ace0b6732d7273a684e',
    messagingSenderId: '782940469195',
    projectId: 'mobiledoc-a1e97',
    storageBucket: 'mobiledoc-a1e97.firebasestorage.app',
    iosBundleId: 'com.mobiledoc.mycoolapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANDDziMRHFcOpSqAlnzi3dPthSLquRgvk',
    appId: '1:399681406363:ios:6b2d04ad520b4728b0cd3e',
    messagingSenderId: '399681406363',
    projectId: 'mobiledocfirebase',
    storageBucket: 'mobiledocfirebase.firebasestorage.app',
    iosBundleId: 'com.example.mobiledoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYwhEMnsl5g7XBUl0eqSJWynmnM016QLw',
    appId: '1:782940469195:web:6d166165747126143a684e',
    messagingSenderId: '782940469195',
    projectId: 'mobiledoc-a1e97',
    authDomain: 'mobiledoc-a1e97.firebaseapp.com',
    storageBucket: 'mobiledoc-a1e97.firebasestorage.app',
    measurementId: 'G-4PC19W25F6',
  );

}