// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACdchX9lfOJR7zeFcMWRXRsjXUN42KJcU',
    appId: '1:399681406363:web:7f1091ac84375de6b0cd3e',
    messagingSenderId: '399681406363',
    projectId: 'mobiledocfirebase',
    authDomain: 'mobiledocfirebase.firebaseapp.com',
    storageBucket: 'mobiledocfirebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVamzL6YI6_vqhMND7-46QBhgparVIFv0',
    appId: '1:399681406363:android:4f223b989434b915b0cd3e',
    messagingSenderId: '399681406363',
    projectId: 'mobiledocfirebase',
    storageBucket: 'mobiledocfirebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANDDziMRHFcOpSqAlnzi3dPthSLquRgvk',
    appId: '1:399681406363:ios:6b2d04ad520b4728b0cd3e',
    messagingSenderId: '399681406363',
    projectId: 'mobiledocfirebase',
    storageBucket: 'mobiledocfirebase.firebasestorage.app',
    iosBundleId: 'com.example.mobiledoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANDDziMRHFcOpSqAlnzi3dPthSLquRgvk',
    appId: '1:399681406363:ios:6b2d04ad520b4728b0cd3e',
    messagingSenderId: '399681406363',
    projectId: 'mobiledocfirebase',
    storageBucket: 'mobiledocfirebase.firebasestorage.app',
    iosBundleId: 'com.example.mobiledoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACdchX9lfOJR7zeFcMWRXRsjXUN42KJcU',
    appId: '1:399681406363:web:7c4ef73ccb1e08e1b0cd3e',
    messagingSenderId: '399681406363',
    projectId: 'mobiledocfirebase',
    authDomain: 'mobiledocfirebase.firebaseapp.com',
    storageBucket: 'mobiledocfirebase.firebasestorage.app',
  );

}